export const athletes = [
    {
        'id': 1,
        'name': 'Daniel Blanco',
        'position': 'Best Position',
        'sport': 'Cycling',
        'favorite_drink': 'Strawberry Cheesecake',
        'image': '/images/sponsoring/Cycling.jpeg',
    },
    {
        'id': 2,
        'name': 'Dan Sexton',
        'position': 'Great Position',
        'sport': 'Golf',
        'favorite_drink': 'Pasta Watermelon',
        'image': '/images/sponsoring/Golf.webp',
    },
    {
        'id': 3,
        'name': 'Han Nguyen',
        'position': 'Even Better Position',
        'sport': 'Baseball',
        'favorite_drink': 'Cambur Test',
        'image': '/images/sponsoring/Running.webp',
    },
    {
        'id': 4,
        'name': 'Vincent RadFORD',
        'position': 'Incredible Position',
        'sport': 'Running',
        'favorite_drink': 'Banana Another',
        'image': '/images/sponsoring/Baseball.jpeg',
    },
    {
        'id': 5,
        'name': 'Tien Hoang',
        'position': 'Winner Position',
        'sport': 'Soccer',
        'favorite_drink': 'Mango Melon',
        'image': '/images/sponsoring/Soccer.jpeg',
    },
];
